FROM node:18.12.1

RUN npm i -g nodemon
RUN mkdir -p /users/gratn/documents/html/vhtml/cursodocker/mongoapp-curso-docker-main/index.js

WORKDIR /users/gratn/documents/html/vhtml/cursodocker/mongoapp-curso-docker-main/index.js

EXPOSE 3000

CMD ["nodemon", "index.js"]
